### ISSUE TITLE
Mugen checkpoint

### ISSUE THREAD

**Issue by xiaoqian-shen** [SongweiGe/TATS#15]
Great work and thanks for kindly releasing both codes and pretrained models! I could access all the checkpoints except the one on Mugen dataset. Could you please upload it to google drive instead of dropbox?

**Comment by SongweiGe** [comment]
Thank you for your interests. Here are the gdrive links to the checkpoints: https://drive.google.com/drive/folders/1uJ9cY2XhwBBC1vEYcg8G3BV_G-OJ5Ugn?usp=sharing. Let me know if you still cannot access them!

**Comment by xiaoqian-shen** [comment]
Thanks very much! This issue can be closed.

**Comment by xiaoqian-shen** [comment]
Hi, is there an official FVD score for MUGEN dataset since I haven't seen it in the paper. I have generated videos with provided pretrained model but the fvd score is quite high. Probably because fvd is sensitive to preprocess or fps. Could you provide an official fvd score for fair comparison? Thanks very much!

**Comment by SongweiGe** [comment]
Due to a version issue of the used MUGEN dataset mentioned [here](https://github.com/SongweiGe/TATS/issues/2#issuecomment-1207314558), we don't have the FVD values calculated. 

I recommend checking the official [codebase](https://github.com/mugen-org/MUGEN_baseline) and table 3 in the [paper](https://arxiv.org/pdf/2204.08058.pdf) for the baseline FVDs.
