### ISSUE TITLE
Checkpoints for TATS-Hierarchical

### ISSUE THREAD

**Issue by Ugness** [SongweiGe/TATS#9]
Hi, thanks for the great work.
Do you have any plan to share the checkpoints and the inference code for TATS-Hierarchical?

If it's hard to share, may I get some metrics or values to monitor about TATS-Hierarchical so that I can reproduce them?

**Comment by SongweiGe** [comment]
Hi Yoo, thank you for your interests in our work. Please find the updated checkpoints and inference code with the hierarchical models under the synthesis section: https://github.com/SongweiGe/TATS#synthesis. 

For the metrics, I usually calculated the FVD manually from time to time to track the training progress, since I found that sometimes even the loss is flattened, the quality can still improve.

**Comment by Ugness** [comment]
Thanks a lot.
